export const GENRES = [
  "Rock",
  "Pop",
  "Electronic", 
  "Folk, World & Country",
  "Funk / Soul",
  "Jazz",
  "Blues",
  "Hip Hop",
  "Stage & Screen",
  "Latin",
  "Reggae",
  "Non-Music",
  "Classical",
  "Children's",
  "Brass & Military",
];

export const YEARS = [
  '2024',
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  '2014',
  '2013',
  '2012',
  '2011',
  '2010',
  '2009',
  '2008',
  '2007',
  '2006',
  '2005',
  '2004',
  '2003',
  '2002',
  '2001',
  '2000',
  '1999',
  '1998',
  '1997',
  '1996',
  '1995',
  '1994',
  '1993',
  '1992',
  '1991',
  '1990',
  '1989',
  '1988',
  '1987',
  '1986',
  '1985',
  '1984',
  '1983',
  '1982',
  '1981',
  '1980',
  '1979',
  '1978',
  '1977',
  '1976',
  '1975',
  '1974',
  '1973',
  '1972',
  '1971',
  '1970',
  '1969',
  '1968',
  '1967',
  '1966',
  '1965',
  '1964',
  '1963',
  '1962',
  '1961',
  '1960',
  '1959',
  '1958',
  '1957',
  '1956',
  '1955',
  '1954',
  '1953',
  '1952',
  '1951',
  '1950',
  '1949',
  '1948',
  '1947',
  '1946',
  '1945',
  '1944',
  '1943',
  '1942',
  '1941',
  '1940',
  '1939',
  '1938',
  '1937',
  '1936',
  '1935',
  '1934',
  '1933',
  '1932',
  '1931',
  '1930',
  '1929',
  '1928',
  '1927',
  '1926',
  '1925',
  '1924',
  '1923',
  '1922',
  '1921',
  '1920',
  '1919',
  '1918',
  '1917',
  '1916',
  '1915',
  '1914',
  '1913',
  '1912',
  '1911',
  '1910',
  '1909',
  '1908',
  '1907',
  '1906',
  '1905',
  '1904',
  '1903',
  '1902',
  '1901',
  '1900',
  '1899',
  '1898',
  '1897',
  '1896',
  '1895',
  '1894',
  '1893',
  '1892',
  '1891',
  '1890',
  '1889',
  '1888',
  '1887',
  '1886',
  '1885',
  '1884',
  '1883',
  '1882',
  '1881',
  '1880',
  '1879',
  '1878',
  '1877',
  '1876',
  '1875',
  '1874',
  '1873',
  '1872',
  '1871',
  '1870',
  '1869',
  '1868',
  '1867',
  '1866',
  '1865',
  '1864',
  '1863',
  '1862',
  '1861',
  '1860',
];

export const COUNTRIES = [
  "US",
  "UK",
  "Germany",
  "France",
  "Japan",
  "Italy",
  "Europe",
  "Canada",
  "Netherlands",
  "Unknown",
  "Spain",
  "Australia",
  "Russia",
  "Sweden",
  "Brazil",
  "Belgium",
  "Greece",
  "Poland",
  "Mexico",
  "Jamaica",
  "Finland",
  "Switzerland",
  "USSR",
  "Denmark",
  "Argentina",
  "Portugal",
  "Norway",
  "Austria",
  "UK & Europe",
  "New Zealand",
  "South Africa",
  "Yugoslavia",
  "Hungary",
  "USA & Canada",
  "Colombia",
  "Ukraine",
  "Turkey",
  "India",
  "Czech Republic",
  "Czechoslovakia",
  "Venezuela",
  "Ireland",
  "Romania",
  "Indonesia",
  "Taiwan",
  "Chile",
  "Peru",
  "South Korea",
  "Israel",
  "Bulgaria",
  "Thailand",
  "Malaysia",
  "Scandinavia",
  "Worldwide",
  "German Democratic Republic (GDR)",
  "China",
  "Croatia",
  "Hong Kong",
  "Philippines",
  "Serbia",
  "Ecuador",
  "UK, Europe & US",
  "Lithuania",
  "Germany, Austria, & Switzerland",
  "Singapore",
  "USA & Europe",
  "Slovakia",
  "Uruguay",
  "Slovenia",
  "Australasia",
  "Australia & New Zealand",
  "Iceland",
  "Bolivia",
  "UK & Ireland",
  "Nigeria",
  "Benelux",
  "USA, Canada & Europe",
  "Estonia",
  "Panama",
  "UK & US",
  "Pakistan",
  "Lebanon",
  "Egypt",
  "Cuba",
  "Costa Rica",
  "Middle East",
  "Latvia",
  "Puerto Rico",
  "Kenya",
  "Belarus",
  "Iran",
  "Guatemala",
  "Morocco",
  "Saudi Arabia",
  "Barbados",
  "Trinidad & Tobago",
  "USA, Canada & UK",
  "Luxembourg",
  "Macedonia",
  "Bosnia & Herzegovina",
  "Czech Republic & Slovakia",
  "Madagascar",
  "Ghana",
  "Zimbabwe",
  "El Salvador",
  "North America (inc Mexico)",
  "Singapore, Malaysia & Hong Kong",
  "Algeria",
  "Dominican Republic",
  "France & Benelux",
  "Ivory Coast",
  "Reunion",
  "Angola",
  "Serbia and Montenegro",
  "Tunisia",
  "Zaire",
  "Georgia",
  "United Arab Emirates",
  "Germany & Switzerland",
  "Malta",
  "Mozambique",
  "Asia",
  "Rhodesia",
  "Cyprus",
  "Mauritius",
  "Azerbaijan",
  "Zambia",
  "Congo, Democratic Republic of the",
  "Nicaragua",
  "Kazakhstan",
  "Syria",
  "Paraguay",
  "Guadeloupe",
  "Senegal",
  "UK & France",
  "UK, Europe & Japan",
  "Bahamas, The",
  "Vietnam",
  "Ethiopia",
  "Suriname",
  "Haiti",
  "Faroe Islands",
  "Albania",
  "Singapore & Malaysia",
  "Moldova, Republic of",
  "South East Asia",
  "Gulf Cooperation Council",
  "South Vietnam",
  "Cameroon",
  "Uzbekistan",
  "South America",
  "Honduras",
  "Martinique",
  "Kuwait",
  "Benin",
  "Sri Lanka",
  "Andorra",
  "Netherlands Antilles",
  "Liechtenstein",
  "Dahomey",
  "Burma",
  "Guinea",
  "Mali",
  "Curaçao",
  "Sudan",
  "Congo, Republic of the",
  "Kosovo",
  "Nepal",
  "Greenland",
  "French Polynesia",
  "Mongolia",
  "Virgin Islands",
  "Southern Rhodesia",
  "Bangladesh",
  "Dutch East Indies",
  "North Korea",
  "Uganda",
  "Armenia",
  "Cape Verde",
  "Bermuda",
  "Central America",
  "Iraq",
  "Seychelles",
  "Cambodia",
  "Guyana",
  "Tanzania",
  "Bahrain",
  "Jordan",
  "Libya",
  "Antigua & Barbuda",
  "Montenegro",
  "Gabon",
  "Palestine",
  "Man, Isle of",
  "Belgian Congo",
  "Afghanistan",
  "Togo",
  "Yemen",
  "Papua New Guinea",
  "Cayman Islands",
  "Monaco",
  "Belize",
  "Fiji",
  "Upper Volta",
  "New Caledonia",
  "East Timor",
  "Austria-Hungary",
  "Laos",
  "Singapore, Malaysia, Hong Kong & Thailand",
  "UK & Germany",
  "Dominica",
  "French Guiana",
  "Aruba",
  "Africa",
  "San Marino",
  "Kyrgyzstan",
  "Turkmenistan",
  "UK, Europe & Israel",
  "Burkina Faso",
  "Marshall Islands",
  "Sierra Leone",
  "Brunei",
  "Saint Kitts and Nevis",
  "Eritrea",
  "Ottoman Empire",
  "Guernsey",
  "North & South America",
  "Namibia",
  "Jersey",
  "Central African Republic",
  "Guam",
  "Grenada",
  "Qatar",
  "Somalia",
  "Botswana",
  "Liberia",
  "Macau",
  "Saint Lucia",
  "Sint Maarten",
  "Lesotho",
  "Maldives",
  "Bhutan",
  "Niger",
  "Protectorate of Bohemia and Moravia",
  "Saint Vincent and the Grenadines",
  "Micronesia, Federated States of",
  "Gambia, The",
  "Malawi",
  "Guinea-Bissau",
  "Indochina",
  "Comoros",
  "Gibraltar",
  "Palau",
  "Korea (pre-1945)",
  "Mauritania",
  "Vatican City",
  "Cook Islands",
  "Tajikistan",
  "Bohemia",
  "Rwanda",
  "Samoa",
  "Oman",
  "South Pacific",
  "Anguilla",
  "Abkhazia",
  "Hong Kong & Thailand",
  "British Virgin Islands",
  "Montserrat",
  "Sao Tome and Principe",
  "Mayotte",
  "Swaziland",
  "Tonga",
  "Vanuatu",
  "Djibouti",
  "South West Africa",
  "West Bank",
  "?",
  "Norfolk Island",
  "Turks and Caicos Islands",
  "Northern Mariana Islands",
  "Solomon Islands",
  "Equatorial Guinea",
  "Southern Sudan",
  "American Samoa",
  "Chad",
  "Falkland Islands",
  "Gaza Strip",
  "Zanzibar",
  "Antarctica",
  "Korea",
  "Nauru",
  "Niue",
  "Pitcairn Islands",
  "Saint Pierre and Miquelon",
  "Tokelau",
  "Tuvalu",
  "Wallis and Futuna",
];

export const STYLES = [
  "Pop Rock",
  "Punk",
  "Alternative Rock",
  "Indie Rock",
  "Hard Rock",
  "Rock & Roll",
  "Hardcore",
  "Heavy Metal",
  "Psychedelic Rock",
  "Folk Rock",
  "Classic Rock",
  "Prog Rock",
  "Black Metal",
  "Blues Rock",
  "Experimental",
  "Death Metal",
  "New Wave",
  "Garage Rock",
  "Soft Rock",
  "Synth-pop",
  "Thrash",
  "Acoustic",
  "Country Rock",
  "Ballad",
  "Vocal",
  "Noise",
  "Art Rock",
  "Doom Metal",
  "Post-Punk",
  "Rockabilly",
  "Avantgarde",
  "Beat",
  "Grindcore",
  "Lo-Fi",
  "Folk",
  "Post Rock",
  "Power Pop",
  "Glam",
  "Rhythm & Blues",
  "Industrial",
  "Goth Rock",
  "Soul",
  "Ambient",
  "Soundtrack",
  "Indie Pop",
  "Emo",
  "Disco",
  "Stoner Rock",
  "Surf",
  "Shoegaze",
  "Electro",
  "Chanson",
  "Oi",
  "Country",
  "Ska",
  "Pop Punk",
  "Doo Wop",
  "Jazz-Rock",
  "Funk",
  "Grunge",
  "Arena Rock",
  "Metalcore",
  "Symphonic Rock",
  "Southern Rock",
  "Downtempo",
  "Nu Metal",
  "Progressive Metal",
  "AOR",
  "Space Rock",
  "Speed Metal",
  "House",
  "Power Metal",
  "Fusion",
  "Krautrock",
  "Europop",
  "Mod",
  "Post-Hardcore",
  "Abstract",
  "Sludge Metal",
  "Schlager",
  "Math Rock",
  "Drone",
  "Leftfield",
  "Easy Listening",
  "Ethereal",
  "Crust",
  "Darkwave",
  "Britpop",
  "Psychobilly",
  "Gothic Metal",
  "Parody",
  "Symphonic Metal",
  "Melodic Death Metal",
  "Lounge",
  "Pop Rap",
  "Dark Ambient",
  "Modern Classical",
  "Goregrind",
  "Neofolk",
  "Dub",
  "RnB/Swing",
  "Euro House",
  "Funk Metal",
  "J-pop",
  "Melodic Hardcore",
  "Techno",
  "Acid Rock",
  "Instrumental",
  "Minimal",
  "Gospel",
  "Atmospheric Black Metal",
  "Folk Metal",
  "Hip Hop",
  "Free Improvisation",
  "Dream Pop",
  "Deathcore",
  "Trip Hop",
  "Dance-pop",
  "Twist",
  "Novelty",
  "Electric Blues",
  "Psychedelic",
  "Reggae",
  "Jazz-Funk",
  "Spoken Word",
  "Theme",
  "Noisecore",
  "Viking Metal",
  "Interview",
  "Post-Metal",
  "Trance",
  "Breakbeat",
  "Score",
  "No Wave",
  "Religious",
  "Coldwave",
  "J-Rock",
  "EBM",
  "Pub Rock",
  "Contemporary Jazz",
  "Comedy",
  "Drum n Bass",
  "IDM",
  "Country Blues",
  "Reggae-Pop",
  "Synthwave",
  "MPB",
  "Swing",
  "Yé-Yé",
  "Celtic",
  "Soul-Jazz",
  "Free Jazz",
  "Brit Pop",
  "New Age",
  "Depressive Black Metal",
  "Deathrock",
  "Bluegrass",
  "Contemporary R&B",
  "Power Violence",
  "Contemporary",
  "Industrial Metal",
  "Technical Death Metal",
  "Latin",
  "Breaks",
  "Big Band",
  "Groove Metal",
  "Big Beat",
  "Eurodance",
  "Neo-Classical",
  "Musical",
  "Avant-garde Jazz",
  "Classical",
  "Smooth Jazz",
  "Latin Jazz",
  "African",
  "Bubblegum",
  "Public Broadcast",
  "Italo-Disco",
  "Funeral Doom Metal",
  "Modern Electric Blues",
  "Chiptune",
  "Pornogrind",
  "Progressive House",
  "Tribal",
  "Dungeon Synth",
  "Dubstep",
  "Cumbia",
  "Chicago Blues",
  "Conscious",
  "Musique Concrète",
  "Samba",
  "Jangle Pop",
  "Hardcore Hip-Hop",
  "Poetry",
  "Swamp Pop",
  "Field Recording",
  "Electro House",
  "Texas Blues",
  "Power Electronics",
  "Afrobeat",
  "Skiffle",
  "Glitch",
  "Breakcore",
  "Flamenco",
  "Tech House",
  "Dialogue",
  "Horror Rock",
  "Kayōkyoku",
  "Honky Tonk",
  "Future Jazz",
  "Bossanova",
  "Bossa Nova",
  "Cha-Cha",
  "Gangsta",
  "Neo Soul",
  "Acid Jazz",
  "Hi NRG",
  "Harmonica Blues",
  "City Pop",
  "Video Game Music",
  "Deep House",
  "Rhythmic Noise",
  "Group Sounds",
  "Bolero",
  "Freestyle",
  "Rumba",
  "Acid",
  "Salsa",
  "Modern",
  "Rocksteady",
  "Berlin-School",
  "Louisiana Blues",
  "Acid House",
  "Cajun",
  "Tango",
  "Piano Blues",
  "Boogie",
  "Mandopop",
  "NDW",
  "Minneapolis Sound",
  "Afro-Cuban",
  "K-Rock",
  "Jump Blues",
  "Promotional",
  "Space-Age",
  "Trap",
  "Cut-up/DJ",
  "Boogie Woogie",
  "Cool Jazz",
  "Happy Hardcore",
  "Rock Opera",
  "Éntekhno",
  "Calypso",
  "Ragga HipHop",
  "Sound Collage",
  "Hillbilly",
  "Light Music",
  "UK Garage",
  "Harsh Noise Wall",
  "Italodance",
  "Progressive Trance",
  "Delta Blues",
  "Speech",
  "Medieval",
  "Chillwave",
  "Political",
  "Garage House",
  "Romantic",
  "Free Funk",
  "Hip-House",
  "Euro-Disco",
  "Opera",
  "Electroclash",
  "Mambo",
  "Radioplay",
  "Dancehall",
  "Gabber",
  "P.Funk",
  "Thug Rap",
  "Roots Reggae",
  "Polka",
  "Vaporwave",
  "Afro-Cuban Jazz",
  "Broken Beat",
  "Dixieland",
  "Music Hall",
  "Ragga",
  "Speedcore",
  "Hard Trance",
  "Bayou Funk",
  "Illbient",
  "Jungle",
  "Nordic",
  "Jazzy Hip-Hop",
  "Jazzdance",
  "Baroque",
  "Education",
  "New Jack Swing",
  "Zydeco",
  "Aboriginal",
  "Bollywood",
  "Grime",
  "Karaoke",
  "Witch House",
  "Laïkó",
  "Ragtime",
  "Hindustani",
  "Pacific",
  "Pachanga",
  "Monolog",
  "Electroacoustic",
  "K-pop",
  "Hard House",
  "Bass Music",
  "New Beat",
  "Cantopop",
  "Sound Art",
  "Gypsy Jazz",
  "Baroque Pop",
  "Canzone Napoletana",
  "Psy-Trance",
  "Brass Band",
  "Phleng Phuea Chiwit",
  "Story",
  "Choral",
  "Merengue",
  "Indian Classical",
  "Nu-Disco",
  "Tribal House",
  "Mariachi",
  "Eurobeat",
  "Cubano",
  "Post-Modern",
  "Tejano",
  "Klezmer",
  "Horrorcore",
  "Educational",
  "Western Swing",
  "Reggaeton",
  "Hawaiian",
  "Special Effects",
  "Bop",
  "Ranchera",
  "Guaracha",
  "Nursery Rhymes",
  "Marches",
  "Swingbeat",
  "Boogaloo",
  "Gogo",
  "Indo-Pop",
  "Dub Techno",
  "Ethno-pop",
  "Volksmusik",
  "Post Bop",
  "Audiobook",
  "Technical",
  "Cloud Rap",
  "Neo-Romantic",
  "Raï",
  "Beguine",
  "Hardstyle",
  "Basque Music",
  "Norteño",
  "Boom Bap",
  "Mizrahi",
  "Minimal Techno",
  "Memphis Blues",
  "Romani",
  "Batucada",
  "Crunk",
  "Chacarera",
  "East Coast Blues",
  "Catalan Music",
  "Hard Techno",
  "Public Service Announcement",
  "Modal",
  "Health-Fitness",
  "Military",
  "Tropical House",
  "Nueva Cancion",
  "Candombe",
  "Therapy",
  "Lovers Rock",
  "Turntablism",
  "Chinese Classical",
  "Highlife",
  "Forró",
  "Conjunto",
  "Screw",
  "Chamamé",
  "Son",
  "Lambada",
  "Sound Poetry",
  "Fado",
  "Appalachian Music",
  "Rebetiko",
  "Goa Trance",
  "Guaguancó",
  "Guajira",
  "Népzene",
  "Soca",
  "Progressive Breaks",
  "Impressionist",
  "Movie Effects",
  "Dark Jazz",
  "Charanga",
  "Hard Bop",
  "Ghetto",
  "G-Funk",
  "Erotic",
  "Hokkien Pop",
  "Trova",
  "Zouk",
  "Porro",
  "Andean Music",
  "Sea Shanties",
  "Axé",
  "J-Core",
  "Break-In",
  "Renaissance",
  "Sermon",
  "Gamelan",
  "Cabaret",
  "Bassline",
  "Enka",
  "Descarga",
  "Tech Trance",
  "Hyperpop",
  "Overtone Singing",
  "Italo House",
  "Bounce",
  "Beatdown",
  "Bhangra",
  "Luk Thung",
  "Beatbox",
  "Britcore",
  "Min'yō",
  "Doomcore",
  "Balearic",
  "Corrido",
  "Quechua",
  "Speed Garage",
  "Bachata",
  "Hands Up",
  "Makina",
  "Baião",
  "Vallenato",
  "Levenslied",
  "Pasodoble",
  "Bengali Music",
  "Barbershop",
  "Deep Techno",
  "Dub Poetry",
  "Jumpstyle",
  "Sephardic",
  "Nueva Trova",
  "Danzon",
  "Progressive Bluegrass",
  "DJ Battle Tool",
  "Dangdut",
  "Hill Country Blues",
  "Juke",
  "Ottoman Classical",
  "Séga",
  "Zemer Ivri",
  "Schranz",
  "Maloya",
  "Soukous",
  "Steel Band",
  "Glitch Hop",
  "Reggae Gospel",
  "Sámi Music",
  "Persian Classical",
  "Choro",
  "Go-Go",
  "Favela Funk",
  "Musette",
  "Música Criolla",
  "Filk",
  "Junkanoo",
  "Yemenite Jewish",
  "Keroncong",
  "Ballroom",
  "Early",
  "Hiplife",
  "Nhạc Vàng",
  "Andalusian Classical",
  "Mouth Music",
  "Donk",
  "Hyphy",
  "Jug Band",
  "Rune Singing",
  "Griot",
  "Electro Swing",
  "Pipe & Drum",
  "Copla",
  "Thai Classical",
  "Piedmont Blues",
  "Marimba",
  "Neo Trance",
  "Son Montuno",
  "Samba-Canção",
  "Liscio",
  "Cambodian Classical",
  "Disco Polo",
  "Huayno",
  "Miami Bass",
  "Timba",
  "Hard Beat",
  "Operetta",
  "Cape Jazz",
  "Footwork",
  "Galician Traditional",
  "Carnatic",
  "Néo Kyma",
  "Baltimore Club",
  "Compas",
  "Gagaku",
  "Joropo",
  "Skweee",
  "Bleep",
  "Champeta",
  "Milonga",
  "Occitan",
  "Zamba",
  "Guarania",
  "Phonk",
  "Serial",
  "Spirituals",
  "Gaita",
  "Nerdcore Techno",
  "Qawwali",
  "Bangladeshi Classical",
  "Mbalax",
  "Ryūkōka",
  "Salegy",
  "Ghetto House",
  "Ghettotech",
  "Sertanejo",
  "UK Street Soul",
  "Cretan",
  "Funkot",
  "Ghazal",
  "Mento",
  "Kwaito",
  "Luk Krung",
  "Plena",
  "UK Funky",
  "Caipira",
  "Marcha Carnavalesca",
  "Mo Lam",
  "Twelve-tone",
  "Vaudeville",
  "Medical",
  "Oratorio",
  "Villancicos",
  "Bomba",
  "Halftime",
  "Korean Court Music",
  "Moombahton",
  "Rapso",
  "Seresta",
  "Waiata",
  "Bongo Flava",
  "Morna",
  "Philippine Classical",
  "Carimbó",
  "Jibaro",
  "Kaseko",
  "Lao Music",
  "Cuatro",
  "Funana",
  "Għana",
  "Shoegazer",
  "Aguinaldo",
  "Tamil Film Music",
  "Sonero",
  "Stride",
  "Azonto",
  "Bambuco",
  "Bubbling",
  "Jota",
  "Lento Violento",
  "Piobaireachd",
  "Sean-nós",
  "Cobla",
  "Freetekno",
  "Guggenmusik",
  "Gwo Ka",
  "Jersey Club",
  "Kizomba",
  "Klasik",
  "Spaza",
  "Taarab",
  "Chutney",
  "Mugham",
  "Shaabi",
  "Shidaiqu",
  "Singeli",
  "Trallalero]",
];

export const FORMATS = [
  "Vinyl",
  "Album",
  "CD",
  "LP",
  "7\"",
  "45 RPM",
  "Single",
  "File",
  "Compilation",
  "Stereo",
  "12\"",
  "Cassette",
  "Promo",
  "MP3",
  "EP",
  "Reissue",
  "Limited Edition",
  "CDr",
  "33 ⅓ RPM",
  "Mono",
  "10\"",
  "Unofficial Release",
  "78 RPM",
  "Shellac",
  "FLAC",
  "Remastered",
  "WAV",
  "Numbered",
  "Maxi-Single",
  "Repress",
  "AAC",
  "White Label",
  "Single Sided",
  "Mixed",
  "DVD",
  "Test Pressing",
  "DVD-Video",
  "Club Edition",
  "Box Set",
  "Mini-Album",
  "Enhanced",
  "Sampler",
  "NTSC",
  "All Media",
  "Special Edition",
  "PAL",
  "Deluxe Edition",
  "Styrene",
  "AIFF",
  "8-Track Cartridge",
  "Mini",
  "Flexi-disc",
  "CD-ROM",
  "Picture Disc",
  "Mixtape",
  "VHS",
  "Advance",
  "ALAC",
  "Misprint",
  "Multichannel",
  "Lathe Cut",
  "Copy Protected",
  "Acetate",
  "Transcription",
  "Jukebox",
  "ogg-vorbis",
  "DVDr",
  "Partially Mixed",
  "HDCD",
  "Reel-To-Reel",
  "SACD",
  "Record Store Day",
  "Hybrid",
  "8\"",
  "Shape",
  "Quadraphonic",
  "Blu-ray",
  "Mispress",
  "Etched",
  "4-Track Stereo",
  "¼\"",
  "7\" Cine Reel",
  "7 ½ ips",
  "6\"",
  "Card Backed",
  "Laserdisc",
  "5½\"",
  "Betacam SP",
  "Partially Unofficial",
  "VCD",
  "MPEG-4 Video",
  "Memory Stick",
  "3 ¾ ips",
  "80 RPM",
  "Cylinder",
  "3.5\"",
  "5\"",
  "Minidisc",
  "Minimax",
  "Edison Disc",
  "Floppy Disk",
  "Pathé Disc",
  "4 Minute",
  "DVD-Audio",
  "MP3 Surround",
  "SECAM",
  "2 Minute",
  "WMA",
  "Business Card",
  "9\"",
  "16\"",
  "4-Track Cartridge",
  "4\"",
  "2-Track Stereo",
  "5\" Cine Reel",
  "DVD-Data",
  "11\"",
  "CD+G",
  "Double Sided",
  "Blu-ray Audio",
  "Blu-ray-R",
  "6½\"",
  "Special Cut",
  "WMV",
  "DCC",
  "DualDisc",
  "29cm",
  "16 ⅔ RPM",
  "U-matic",
  "Ambisonic",
  "XRCD",
  "AIFC",
  "2-Track Mono",
  "CDV",
  "5.25\"",
  "15 ips",
  "Betamax",
  "27cm",
  "AVCD",
  "90 RPM",
  "8 ⅓ RPM",
  "3\"",
  "10.5\" NAB Reel",
  "MPEG-4",
  "DAT",
  "25cm",
  "MOV",
  "PlayTape",
  "CDi",
  "DSF",
  "Microcassette",
  "Minidisc",
  "Minimax",
  "Edison Disc",
  "Floppy Disk",
  "Pathé Disc",
  "4 Minute",
  "DVD-Audio",
  "MP3 Surround",
  "SECAM",
  "2 Minute",
  "WMA",
  "Business Card",
  "9\"",
  "16\"",
  "4-Track Cartridge",
  "4\"",
  "2-Track Stereo",
  "5\" Cine Reel",
  "DVD-Data",
  "11\"",
  "CD+G",
  "Double Sided",
  "Blu-ray Audio",
  "Blu-ray-R",
  "6½\"",
  "Special Cut",
  "WMV",
  "DCC",
  "DualDisc",
  "29cm",
  "16 ⅔ RPM",
  "U-matic",
  "Ambisonic",
  "XRCD",
  "AIFC",
  "2-Track Mono",
  "CDV",
  "5.25\"",
  "15 ips",
  "Betamax",
  "27cm",
  "AVCD",
  "90 RPM",
  "8 ⅓ RPM",
  "3\"",
  "10.5\" NAB Reel",
  "MPEG-4",
  "DAT",
  "25cm",
  "MOV",
  "PlayTape",
  "CDi",
  "DSF",
  "Microcassette",
  "Minidisc",
  "Minimax",
  "Edison Disc",
  "Floppy Disk",
  "Pathé Disc",
  "4 Minute",
  "DVD-Audio",
  "MP3 Surround",
  "SECAM",
  "2 Minute",
  "WMA",
  "Business Card",
  "9\"",
  "16\"",
  "4-Track Cartridge",
  "4\"",
  "2-Track Stereo",
  "5\" Cine Reel",
  "DVD-Data",
  "11\"",
  "CD+G",
  "Double Sided",
  "Blu-ray Audio",
  "Blu-ray-R",
  "6½\"",
  "Special Cut",
  "WMV",
  "DCC",
  "DualDisc",
  "29cm",
  "16 ⅔ RPM",
  "U-matic",
  "Ambisonic",
  "XRCD",
  "AIFC",
  "2-Track Mono",
  "CDV",
  "5.25\"",
  "15 ips",
  "Betamax",
  "27cm",
  "AVCD",
  "90 RPM",
  "8 ⅓ RPM",
  "3\"",
  "10.5\" NAB Reel",
  "MPEG-4",
  "DAT",
  "25cm",
  "MOV",
  "PlayTape",
  "CDi",
  "DSF",
  "Microcassette",
  "Minidisc",
  "Minimax",
  "Edison Disc",
  "Floppy Disk",
  "Pathé Disc",
  "4 Minute",
  "DVD-Audio",
  "MP3 Surround",
  "SECAM",
  "2 Minute",
  "WMA",
  "Business Card",
  "9\"",
  "16\"",
  "4-Track Cartridge",
  "4\"",
  "2-Track Stereo",
  "5\" Cine Reel",
  "DVD-Data",
  "11\"",
  "CD+G",
  "Double Sided",
  "Blu-ray Audio",
  "Blu-ray-R",
  "6½\"",
  "Special Cut",
  "WMV",
  "DCC",
  "DualDisc",
  "29cm",
  "16 ⅔ RPM",
  "U-matic",
  "Ambisonic",
  "XRCD",
  "AIFC",
  "2-Track Mono",
  "CDV",
  "5.25\"",
  "15 ips",
  "Betamax",
  "27cm",
  "AVCD",
  "90 RPM",
  "8 ⅓ RPM",
  "3\"",
  "10.5\" NAB Reel",
  "MPEG-4",
  "DAT",
  "25cm",
  "MOV",
  "PlayTape",
  "CDi",
  "DSF",
  "Microcassette",
  "Minidisc",
  "Minimax",
  "Edison Disc",
  "Floppy Disk",
  "Pathé Disc",
  "4 Minute",
  "DVD-Audio",
  "MP3 Surround",
  "SECAM",
  "2 Minute",
  "WMA",
  "Business Card",
  "9\"",
  "16\"",
  "4-Track Cartridge",
  "4\"",
  "2-Track Stereo",
  "5\" Cine Reel",
  "DVD-Data",
  "11\"",
  "CD+G",
  "Double Sided",
  "Blu-ray Audio",
  "Blu-ray-R",
  "6½\"",
  "Special Cut",
  "WMV",
  "DCC",
  "DualDisc",
  "29cm",
  "16 ⅔ RPM",
  "U-matic",
  "Ambisonic",
  "XRCD",
  "AIFC",
  "2-Track Mono",
  "CDV",
  "5.25\"",
  "15 ips",
  "Betamax",
  "27cm",
  "AVCD",
  "90 RPM",
  "8 ⅓ RPM",
  "3\"",
  "10.5\" NAB Reel",
  "MPEG-4",
  "DAT",
  "25cm",
]; 
